### PR TITLE
Remove listeners after all requests are done

### PR DESCRIPTION
**Pull request by mendelgusmao**
I was scraping a page that does a lot of XHR requests and noticed this message

`(node:81195) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 request listeners added to [Page]. Use emitter.setMaxListeners() to increase limit`

This patch prevents the aforementioned memory leak by removing our listeners after all XHR are finished.

### CODE REVIEW

**Comment by jtassin** [comment]
Hi @mendelgusmao 

This i s a great idea, thx.

I only have a problem with such feature with my application.
My application is a SPA and I need to perform several times `waitForAllXhrFinished` during the page life time.

Maybe we can and a parameter `removeListener` to `waitForAllXhrFinished` . And perform the removeListeners conditionaly.

**Comment by mendelgusmao** [comment]
@jtassin Your comment shown me that I was actually using your lib the wrong way by creating a new PendingXHR for every action expecting a XHR to happen. Thank you!

Anyway, here is a new proposal: waitOnceForAllXhrFinished(). It does the waitForAllXhrFinished as usual, then clean the listeners. I think this is a more OO approach.

**Comment by jtassin** [comment]
> Anyway, here is a new proposal: waitOnceForAllXhrFinished(). It does the waitForAllXhrFinished as usual, then clean the listeners. I think this is a more OO approach.

OK for  a new function `waitOnceForAllXhrFinished` that will remove listeners after itself 👍 I agree with you that the behaviour would be much better like this.

**Comment by sedenardi** [comment]
Hi @jtassin, any idea when you could push the new `waitOnceForAllXhrFinished` function to `npm`? I'm reusing puppeteer pages for scraping, and would like to use this to attach (and clean up) multiple instances of `PendingXHR` to the same page.

Thanks for your great work on this library.

**Comment by jtassin** [comment]
hi @sedenardi this feature is included in the 2.2.0 version

**Pull request merged**
